---
name: ci
env:
  BOGUS_SECRET: ${{ secrets.BOGUS_SECRET }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test secrets
        run: |
          if [ -z "${BOGUS_SECRET}" ]; then
            exit 1
          fi
