---
name: ci
env:
  BOGUS_SECRET: ${{ secrets.BOGUS_SECRET }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shfmt:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel-20210131.0.14634

    steps:
      - uses: actions/checkout@v2
      - name: Test secrets
        run: |
          if [ -z "${BOGUS_SECRET}" ]; then
            exit 1
          fi
